version: '3.9'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pg15_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  pg15_data: {}
